### ISSUE TITLE
Jenkins build fails after merge with JSONDecodeError

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-covid-19#456]
### Describe the bug

The merge step of the Jenkins build appears to complete as expected, but immediately afterward, the following error is raised:
```
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

Full stack trace:
```
00:25:48  [KGX][cli_utils.py][               merge] INFO: Merged graph has 574778 nodes and 24145556 edges
00:31:09  [KGX][cli_utils.py][               merge] INFO: Writing merged graph to merged-kg-tsv
00:31:17  Traceback (most recent call last):
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/requests/models.py", line 910, in json
00:31:17      return complexjson.loads(self.text, **kwargs)
00:31:17    File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
00:31:17      return _default_decoder.decode(s)
00:31:17    File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
00:31:17      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
00:31:17    File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
00:31:17      raise JSONDecodeError("Expecting value", s, err.value) from None
00:31:17  json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
00:31:17  
00:31:17  During handling of the above exception, another exception occurred:
00:31:17  
00:31:17  Traceback (most recent call last):
00:31:17    File "run.py", line 166, in <module>
00:31:17      cli()
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
00:31:17      return self.main(*args, **kwargs)
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
00:31:17      rv = self.invoke(ctx)
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
00:31:17      return _process_result(sub_ctx.command.invoke(sub_ctx))
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
00:31:17      return ctx.invoke(self.callback, **ctx.params)
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
00:31:17      return callback(*args, **kwargs)
00:31:17    File "run.py", line 84, in merge
00:31:17      load_and_merge(yaml, processes)
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/kg_covid_19/merge_utils/merge_kg.py", line 33, in load_and_merge
00:31:17      merged_graph = merge(yaml_file, processes=processes)
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/kgx/cli/cli_utils.py", line 753, in merge
00:31:17      transformer = Transformer()
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/kgx/transformer.py", line 109, in __init__
00:31:17      self.store = self.get_source("graph")
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/kgx/transformer.py", line 425, in get_source
00:31:17      return s(self)
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/kgx/source/graph_source.py", line 19, in __init__
00:31:17      super().__init__(owner)
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/kgx/source/source.py", line 27, in __init__
00:31:17      self.prefix_manager = PrefixManager()
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/kgx/prefix_manager.py", line 38, in __init__
00:31:17      context = get_jsonld_context()
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/kgx/config.py", line 61, in get_jsonld_context
00:31:17      content = requests.get(filepath).json()
00:31:17    File "/var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.8/site-packages/requests/models.py", line 917, in json
00:31:17      raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
00:31:17  requests.exceptions.JSONDecodeError: [Errno Expecting value] 
00:31:17  <?xml version="1.0" encoding="utf-8"?>
00:31:17  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
00:31:17   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
00:31:17  <html>
00:31:17    <head>
00:31:17      <title>503 first byte timeout</title>
00:31:17    </head>
00:31:17    <body>
00:31:17      <h1>Error 503 first byte timeout</h1>
00:31:17      <p>first byte timeout</p>
00:31:17      <h3>Guru Mediation:</h3>
00:31:17      <p>Details: cache-pao17435-PAO 1654144276 2648075348</p>
00:31:17      <hr>
00:31:17      <p>Varnish cache server</p>
00:31:17    </body>
00:31:17  </html>
00:31:17  : 1
```

### To Reproduce

See build 237 on June 1 2022

## Expected behavior

Steps after merge should look like:
```
00:18:39  [KGX][cli_utils.py][               merge] INFO: Merged graph has 574778 nodes and 24145556 edges
00:23:00  [KGX][cli_utils.py][               merge] INFO: Writing merged graph to merged-kg-tsv
01:38:36  [KGX][cli_utils.py][               merge] INFO: Writing merged graph to merged-kg-nt
[Pipeline] sh
13:22:29  + cp merged_graph_stats.yaml merged_graph_stats_20220502.yaml
[Pipeline] sh
13:22:29  + tar -rvf data/merged/merged-kg.tar merged_graph_stats_20220502.yaml
13:22:29  merged_graph_stats_20220502.yaml
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Make blazegraph journal)
[Pipeline] dir
13:22:30  Running in /var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master@2/gitrepo/blazegraph
...
```

### Version

561af42bff4c7f2455c5c14142f40eadfe1f17c8

**Comment by caufieldjh** [comment]
Didn't encounter this error in the 20220610 build - closing and will reopen if it happens again
